ci: straighten arch conditions

diff --git a/.gitea/workflows/build.yaml b/.gitea/workflows/build.yaml
--- a/.gitea/workflows/build.yaml
+++ b/.gitea/workflows/build.yaml
@@ -29,6 +29,7 @@ jobs:
       APP_VERSION: ${{ steps.vars.outputs.APP_VERSION }}
       BARM32: ${{ steps.vanco.outputs.BARM32 }}
       BARM64: ${{ steps.vanco.outputs.BARM64 }}
+      BARM_BOTH: ${{ steps.vanco.outputs.BARM_BOTH }}
       SHA32_WV: ${{ steps.hash.outputs.SHA32_WV }}
       SHA64_WV: ${{ steps.hash.outputs.SHA64_WV }}
       SHA32_BRW: ${{ steps.hash.outputs.SHA32_BRW }}
@@ -87,26 +88,19 @@ jobs:
         webview_ver=$(echo "${latestVanadium}" | cut -d '.' -f 1-4)
         echo "WV_VER=$webview_ver" >> $GITHUB_ENV
 
-        BARM32=unset
-        BARM64=unset
-        
-        if [ "${INPUT_BUILDARCH}" == "arm_both" ]; then
-          BARM32=arm32
-          BARM64=arm64
-        else
-          if [ "${INPUT_BUILDARCH}" == "arm32" ]; then
-            BARM32=arm32
-          fi
-          if [ "${INPUT_BUILDARCH}" == "arm64" ]; then
-            BARM64=arm64
-          fi
-        fi
-        echo "BARM32: $BARM32, BARM64: $BARM64"
-        echo "BARM32=$BARM32" >> $GITHUB_OUTPUT
-        echo "BARM64=$BARM64" >> $GITHUB_OUTPUT
+        echo "BARM32=0" >> $GITHUB_OUTPUT
+        echo "BARM64=0" >> $GITHUB_OUTPUT
+        echo "BARM_BOTH=0" >> $GITHUB_OUTPUT
 
-    - name: "Build arm"
-      if: ${{ contains(inputs.buildarch, 'arm32') }}
+        case ${INPUT_BUILDARCH} in
+          arm32) echo "BARM32=1" >> $GITHUB_OUTPUT ;;
+          arm64) echo "BARM64=1" >> $GITHUB_OUTPUT ;;
+           *) echo "BARM_BOTH=1" >> $GITHUB_OUTPUT ;; # both is default so any invalid or empty input will build both
+        esac
+        echo "BARM32: $BARM32, BARM64: $BARM64, BARM_BOTH=$BARM_BOTH"
+
+    - name: "Build arm32"
+      if: ${{ steps.vanco.outputs.BARM32 }} == 1
       shell: bash
       run: |
         ulimit -a
@@ -115,7 +109,7 @@ jobs:
         ./build.sh -V ${{ github.workspace }}/vanadium -C ${{ github.workspace }}/chromium -a arm
 
     - name: "Build arm64"
-      if: ${{ contains(inputs.buildarch, 'arm64') }}
+      if: ${{ steps.vanco.outputs.BARM64 }} == 1
       shell: bash
       run: |
         cd aosmium
@@ -123,7 +117,7 @@ jobs:
         ./build.sh -V ${{ github.workspace }}/vanadium -C ${{ github.workspace }}/chromium -a arm64
 
     - name: "Build arm & arm64"
-      if: ${{ contains(inputs.buildarch, 'arm_both') }}
+      if: ${{ steps.vanco.outputs.BARM_BOTH }} == 1
       shell: bash
       run: |
         ulimit -a
@@ -142,12 +136,12 @@ jobs:
         BARM64=${{ steps.vanco.outputs.BARM64 }}
         echo "BARM32: $BARM32, BARM64: $BARM64"
 
-        [ "$BARM32" == "arm32" ] && APPV32=$(../tools/aapt2 dump badging prebuilt/arm/webview-unsigned.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
-        [ "$BARM64" == "arm64" ] && APPV64=$(../tools/aapt2 dump badging prebuilt/arm64/webview-unsigned.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
+        [ "$BARM32" == "1" ] && APPV32=$(../tools/aapt2 dump badging prebuilt/arm/webview-unsigned.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
+        [ "$BARM64" == "1" ] && APPV64=$(../tools/aapt2 dump badging prebuilt/arm64/webview-unsigned.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
         OVER=v$(date +%Y.%m.%d)
         
-        [ "$BARM32" == "arm32" ] && [ -z "$APPV32" ] && echo "ERROR: empty APPV32 detected" && exit 3
-        [ "$BARM64" == "arm64" ] && [ -z "$APPV64" ] && echo "ERROR: empty APPV64 detected" && exit 3
+        [ "$BARM32" == "1" ] && [ -z "$APPV32" ] && echo "ERROR: empty APPV32 detected" && exit 3
+        [ "$BARM64" == "1" ] && [ -z "$APPV64" ] && echo "ERROR: empty APPV64 detected" && exit 3
         [ -z "$OVER" ] && echo "ERROR: empty OVER detected" && exit 3
 
         if [ "$APPV32" != "$APPV64" ];then
@@ -158,7 +152,7 @@ jobs:
             OVER="$APPV64"
         fi
 
-        if [ "$BARM64" == "arm64" ];then
+        if [ "$BARM64" == "1" ];then
           APPV64_BRW=$(../tools/aapt2 dump badging prebuilt/arm64/browser-unsigned.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
           if [ "$APPV64" != "$APPV64_BRW" ];then
             echo "WARNING: webview and browser versions differ ($APPV64 / $APPV64_BRW)!"
@@ -166,23 +160,23 @@ jobs:
         fi
 
         echo "APP_VERSION=${OVER}" >> $GITHUB_ENV
-        [ "$BARM" == "arm32" ] && echo "APP32_VERSION=${APPV32}" >> $GITHUB_ENV
-        [ "$BARM64" == "arm64" ] && echo "APP64_VERSION=${APPV64}" >> $GITHUB_ENV
+        [ "$BARM32" == "1" ] && echo "APP32_VERSION=${APPV32}" >> $GITHUB_ENV
+        [ "$BARM64" == "1" ] && echo "APP64_VERSION=${APPV64}" >> $GITHUB_ENV
         git_sha_short=$(git rev-parse --short "$GITHUB_SHA")
         echo "git_sha_short=$git_sha_short" >> $GITHUB_ENV
 
         echo "APP_VERSION=${OVER}" >> $GITHUB_OUTPUT
         echo "git_sha_short=$git_sha_short" >> $GITHUB_OUTPUT
 
-        [ "$BARM" == "arm32" ] && echo "APP32 version is: $APPV32 ($git_sha_short)"
-        [ "$BARM64" == "arm64" ] && echo "APP64 version is: $APPV64 ($git_sha_short)"
+        [ "$BARM32" == "1" ] && echo "APP32 version is: $APPV32 ($git_sha_short)"
+        [ "$BARM64" == "1" ] && echo "APP64 version is: $APPV64 ($git_sha_short)"
 
         mkdir apks
 
-        [ "$BARM32" == "arm32" ] && cp prebuilt/arm/web*.apk apks/webview32.apk
-        [ "$BARM32" == "arm32" ] && cp prebuilt/arm/browser*.apk apks/browser32.apk
-        [ "$BARM64" == "arm64" ] && cp prebuilt/arm64/web*.apk apks/webview64.apk
-        [ "$BARM64" == "arm64" ] && cp prebuilt/arm64/browser*.apk apks/browser64.apk
+        [ "$BARM32" == "1" ] && cp prebuilt/arm/web*.apk apks/webview32.apk
+        [ "$BARM32" == "1" ] && cp prebuilt/arm/browser*.apk apks/browser32.apk
+        [ "$BARM64" == "1" ] && cp prebuilt/arm64/web*.apk apks/webview64.apk
+        [ "$BARM64" == "1" ] && cp prebuilt/arm64/browser*.apk apks/browser64.apk
 
     - name: set up JDK
       uses: actions/setup-java@v3
@@ -217,7 +211,7 @@ jobs:
 
         cd aosmium/apks
 
-        if [ "$BARM64" == "arm64" ];then
+        if [ "$BARM64" == "1" ];then
           sha512sum webview64-signed.apk > webview64-signed.apk.sha512
           sha512sum browser64-signed.apk > browser64-signed.apk.sha512
           cp webview64-signed.apk AOSmium-Webview64_${{ steps.vars.outputs.APP_VERSION }}.apk
@@ -228,7 +222,7 @@ jobs:
           echo "SHA64_BRW=$(cat browser64-signed.apk.sha512 | cut -d ' ' -f1)" >> $GITHUB_OUTPUT
         fi
 
-        if [ "$BARM32" == "arm32" ];then
+        if [ "$BARM32" == "1" ];then
           sha512sum webview32-signed.apk > webview32-signed.apk.sha512
           sha512sum browser32-signed.apk > browser32-signed.apk.sha512
           cp webview32-signed.apk AOSmium-Webview32_${{ steps.vars.outputs.APP_VERSION }}.apk
